src/attachments/urls.py
from django.urls import path

from attachments import views

app_name = 'attachments'
urlpatterns = [
    path('<str:id>/<str:name>', views.GetAttachmentAPIView.as_view(), name='get-attachment'),
    path('upload-to-task', views.UploadTaskAttachmentAPIView.as_view(), name='upload-task-attachment'),
    path('upload-to-issue', views.UploadIssueAttachmentAPIView.as_view(), name='upload-issue-attachment'),
]

src/dashboard/adls/urls.py
from django.urls import path

from dashboard.adls import views

app_name = 'adls'
urlpatterns = [
    path('', views.AdlListView.as_view(), name='list'),
    path('<slug:id>/', views.AdlDetailView.as_view(), name='detail'),
    path('toggle-status/<slug:id>/', views.ToggleAdlStatusView.as_view(), name='toggle_status'),
    path('edit-profile/<slug:id>/', views.EditAdlProfileFormView.as_view(), name='edit_profile'),
]

src/dashboard/grm/urls.py
from django.urls import path

from dashboard.grm import views

app_name = 'grm'
urlpatterns = [
    path('', views.DashboardTemplateView.as_view(), name='dashboard'),
    path('start-new-issue', views.StartNewIssueView.as_view(), name='start_new_issue'),
    path('upload-issue-attachment/<int:issue>/', views.UploadIssueAttachmentFormView.as_view(),
         name='upload_issue_attachment'),
    path('delete-issue-attachment/<int:issue>/<str:attachment>/', views.IssueAttachmentDeleteView.as_view(),
         name='delete_issue_attachment'),
    path('issue-attachments/<int:issue>/', views.IssueAttachmentListView.as_view(), name='issue_attachments'),
    path('new-issue-step-1/<int:issue>/', views.NewIssueContactFormView.as_view(), name='new_issue_step_1'),
    path('new-issue-step-2/<int:issue>/', views.NewIssuePersonFormView.as_view(), name='new_issue_step_2'),
    path('new-issue-step-3/<int:issue>/', views.NewIssueDetailsFormView.as_view(), name='new_issue_step_3'),
    path('new-issue-step-4/<int:issue>/', views.NewIssueLocationFormView.as_view(), name='new_issue_step_4'),
    path('new-issue-step-5/<int:issue>/', views.NewIssueConfirmFormView.as_view(), name='new_issue_step_5'),
    path('new-issue-step-6/<int:issue>/', views.NewIssueConfirmationFormView.as_view(), name='new_issue_step_6'),
    path('review-issues', views.ReviewIssuesFormView.as_view(), name='review_issues'),
    path('issue-list', views.IssueListView.as_view(), name='issue_list'),
    path('issue-detail/<int:issue>/', views.IssueDetailsFormView.as_view(), name='issue_detail'),
    path('get-sensitive-issue-data/', views.GetSensitiveIssueDataView.as_view(), name='get_sensitive_issue_data'),
    path('edit-issue/<int:issue>/', views.EditIssueView.as_view(), name='edit_issue'),
    path('add-comment-to-issue/<int:issue>/', views.AddCommentToIssueView.as_view(), name='add_comment_to_issue'),
    path('issue-comments/<int:issue>/', views.IssueCommentListView.as_view(), name='issue_comments'),
    path('issue-status-buttons/<int:issue>/', views.IssueStatusButtonsTemplateView.as_view(),
         name='issue_status_buttons'),
    path('submit-issue-open-status/<int:issue>/', views.SubmitIssueOpenStatusView.as_view(),
         name='submit_issue_open_status'),
    path('submit-issue-research-result/<int:issue>/', views.SubmitIssueResearchResultFormView.as_view(),
         name='submit_issue_research_result'),
    path('submit-issue-reject-reason/<int:issue>/', views.SubmitIssueRejectReasonFormView.as_view(),
         name='submit_issue_reject_reason'),
    path('get-choices-for-next-administrative-level', views.GetChoicesForNextAdministrativeLevelView.as_view(),
         name='get_choices_for_next_administrative_level'),
    path('get-ancestor-administrative-levels', views.GetAncestorAdministrativeLevelsView.as_view(),
         name='get_ancestor_administrative_levels'),
]

src/dashboard/urls.py
from django.conf.urls import include
from django.urls import path

app_name = 'dashboard'
urlpatterns = [
    path('', include('dashboard.authentication.urls')),
    path('diagnostics/', include('dashboard.diagnostics.urls')),
    path('administrative-levels/', include('dashboard.adls.urls')),
    # path('participatory-budget/', include('dashboard.participatory_budget.urls')),
    # path('subprojects/', include('dashboard.subprojects.urls')),
    path('grm/', include('dashboard.grm.urls')),
    path('logs/', include('dashboard.logs.urls')),
    path('couchdb-proxy/', include('dashboard.couchdb_proxy.urls')),
]

src/grm/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

handler400 = 'dashboard.authentication.views.handler400'
handler403 = 'dashboard.authentication.views.handler403'
handler404 = 'dashboard.authentication.views.handler404'
handler500 = 'dashboard.authentication.views.handler500'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('attachments/', include('attachments.urls')),
    path('authentication/', include('authentication.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('dashboard.urls')),
]

schema_view = get_schema_view(
    openapi.Info(
        title="GRM API Documentation",
        default_version='v1',
        description="Test Documentation",
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    ]

src/dashboard/forms/widgets.py
from django import forms


class RadioSelect(forms.RadioSelect):
    input_type = 'radio'
    option_template_name = 'widgets/radio_option.html'

src/dashboard/grm/forms.py
from django import forms
from django.conf import settings
from django.utils.translation import gettext_lazy as _

from authentication.models import get_government_worker_choices
from client import get_db
from dashboard.forms.widgets import RadioSelect
from dashboard.grm import CHOICE_CONTACT, CITIZEN_TYPE_CHOICES, CONTACT_CHOICES, GENDER_CHOICES, MEDIUM_CHOICES
from grm.utils import (
    get_administrative_region_choices, get_base_administrative_id, get_administrative_regions_by_level,
    get_issue_age_group_choices, get_issue_category_choices, get_issue_citizen_group_1_choices,
    get_issue_citizen_group_2_choices, get_issue_status_choices, get_issue_type_choices, get_region_choices,
    get_prefecture_choices
)

COUCHDB_GRM_DATABASE = settings.COUCHDB_GRM_DATABASE
MAX_LENGTH = 65000


class NewIssueContactForm(forms.Form):
    contact_medium = forms.ChoiceField(label=_('Comment le citoyen souhaite-t-il être contaté?'), widget=RadioSelect,
                                       choices=MEDIUM_CHOICES)
    contact_type = forms.ChoiceField(label='', required=False, choices=CONTACT_CHOICES)
    contact = forms.CharField(label='', required=False)

    def __init__(self, *args, **kwargs):
        initial = kwargs.get('initial')
        doc_id = initial.get('doc_id')
        super().__init__(*args, **kwargs)

        grm_db = get_db(COUCHDB_GRM_DATABASE)

        self.fields['contact'].widget.attrs["placeholder"] = _("SVP Entrer les informations de contact")

        document = grm_db[doc_id]
        if 'contact_medium' in document:
            self.fields['contact_medium'].initial = document['contact_medium']
            if document['contact_medium'] == CHOICE_CONTACT:
                if 'type' in document['contact_information'] and document['contact_information']['type']:
                    self.fields['contact_type'].initial = document['contact_information']['type']
                if 'contact' in document['contact_information'] and document['contact_information']['contact']:
                    self.fields['contact'].initial = document['contact_information']['contact']
            else:
                self.fields['contact'].widget.attrs["class"] = "hidden"


class NewIssuePersonForm(forms.Form):
    citizen = forms.CharField(label=_('Entrer le nom du citoyen'), required=False,
                              help_text=_('Ce champ n\'est pas obligatoire'))
    citizen_type = forms.ChoiceField(label=_(''), widget=RadioSelect, required=False,
                                     choices=CITIZEN_TYPE_CHOICES, help_text=_('Ce champ n\'est pas obligatoire'))
    citizen_age_group = forms.ChoiceField(label=_('Entrer la tranche d\'âge du citoyen'), required=False,
                                          help_text=_('Ce champ n\'est pas obligatoire'))
    gender = forms.ChoiceField(label=_('Choisissez le sexe'), required=False, help_text=_('Ce champ n\'est pas obligatoire'),
                               choices=GENDER_CHOICES)
    citizen_group_1 = forms.ChoiceField(label=_('Nationalité du citoyen'), required=False,
                                        help_text=_('Ce champ n\'est pas obligatoire'))

    def __init__(self, *args, **kwargs):
        initial = kwargs.get('initial')
        doc_id = initial.get('doc_id')
        super().__init__(*args, **kwargs)

        grm_db = get_db(COUCHDB_GRM_DATABASE)

        citizen_age_groups = get_issue_age_group_choices(grm_db)
        self.fields['citizen_age_group'].widget.choices = citizen_age_groups
        self.fields['citizen_age_group'].choices = citizen_age_groups

        citizen_group_1_choices = get_issue_citizen_group_1_choices(grm_db)
        self.fields['citizen_group_1'].widget.choices = citizen_group_1_choices
        self.fields['citizen_group_1'].choices = citizen_group_1_choices

        document = grm_db[doc_id]

        if 'citizen' in document:
            self.fields['citizen'].initial = document['citizen']

        if 'citizen_type' in document:
            self.fields['citizen_type'].initial = document['citizen_type']

        if 'citizen_age_group' in document and document['citizen_age_group']:
            self.fields['citizen_age_group'].initial = document['citizen_age_group']['_id']

        if 'gender' in document:
            self.fields['gender'].initial = document['gender']

        if 'citizen_group_1' in document and document['citizen_group_1']:
            self.fields['citizen_group_1'].initial = document['citizen_group_1']['_id']


class NewIssueDetailsForm(forms.Form):
    intake_date = forms.DateTimeField(label=_('Date du jour'), input_formats=['%d/%m/%Y'],
                                      help_text="Date à laquelle le problème est enregistré")
    issue_date = forms.DateTimeField(label=_('Date du problème'), input_formats=['%d/%m/%Y'],
                                     help_text="Date à laquelle le problème est survenu")
    issue_type = forms.ChoiceField(label=_('Que signalez-vous'))
    category = forms.ChoiceField(label=_('Secteur d\'activité'))
    description = forms.CharField(label=_('Décrivez brièvement le problème'), max_length=2000, widget=forms.Textarea(
        attrs={'rows': '3', 'placeholder': _("S'il vous plaît decriver le problème")}))
    ongoing_issue = forms.BooleanField(label=_('Evénement en cours ou occurrences multiples'),
                                       widget=forms.CheckboxInput, required=False)

    def __init__(self, *args, **kwargs):
        initial = kwargs.get('initial')
        doc_id = initial.get('doc_id')
        super().__init__(*args, **kwargs)

        grm_db = get_db(COUCHDB_GRM_DATABASE)
        types = get_issue_type_choices(grm_db)
        self.fields['issue_type'].widget.choices = types
        self.fields['issue_type'].choices = types
        categories = get_issue_category_choices(grm_db)
        self.fields['category'].widget.choices = categories
        self.fields['category'].choices = categories

        self.fields['intake_date'].widget.attrs['class'] = self.fields['issue_date'].widget.attrs[
            'class'] = 'form-control datetimepicker-input'
        self.fields['intake_date'].widget.attrs['data-target'] = '#intake_date'
        self.fields['issue_date'].widget.attrs['data-target'] = '#issue_date'

        document = grm_db[doc_id]
        if 'description' in document and document['description']:
            self.fields['description'].initial = document['description']
        if 'issue_type' in document and document['issue_type']:
            self.fields['issue_type'].initial = document['issue_type']['_id']
        if 'category' in document and document['category']:
            self.fields['category'].initial = document['category']['_id']
        if 'ongoing_issue' in document:
            self.fields['ongoing_issue'].initial = document['ongoing_issue']


class NewIssueLocationForm(forms.Form):
    region = forms.ChoiceField()
    prefecture = forms.ChoiceField()

    def __init__(self, *args, **kwargs):
        initial = kwargs.get('initial')
        doc_id = initial.get('doc_id')
        super().__init__(*args, **kwargs)

        grm_db = get_db(COUCHDB_GRM_DATABASE)

        regions = get_region_choices(grm_db)
        self.fields['region'].label = "Choisr la Région"
        self.fields['region'].choices = regions
        self.fields['region'].widget.choices = regions

        prefectures = get_prefecture_choices(grm_db)
        self.fields['prefecture'].label = "Choisir la prefecture"
        self.fields['prefecture'].choices = prefectures
        self.fields['prefecture'].widget.choices = prefectures

        #eadl_db = get_db()
        #label = get_administrative_regions_by_level(eadl_db)[0]['administrative_level'].title()


        #administrative_region_choices = get_administrative_region_choices(eadl_db)
        #self.fields['administrative_region'].widget.choices = administrative_region_choices
        #self.fields['administrative_region'].choices = administrative_region_choices
        #self.fields['administrative_region'].widget.attrs['class'] = "region"
        #self.fields['administrative_region_value'].widget.attrs['class'] = "hidden"

        #grm_db = get_db(COUCHDB_GRM_DATABASE)
        document = grm_db[doc_id]
        if 'region' in document and document['region']:
            self.fields['region'].initial = document['region']['_id']
        if 'prefecture' in document and document['prefecture']:
            self.fields['prefecture'].initial = document['prefecture']['_id']


class NewIssueConfirmForm(NewIssueLocationForm, NewIssueDetailsForm, NewIssuePersonForm, NewIssueContactForm):

    def __init__(self, *args, **kwargs):
        NewIssueContactForm.__init__(self, *args, **kwargs)
        NewIssuePersonForm.__init__(self, *args, **kwargs)
        NewIssueDetailsForm.__init__(self, *args, **kwargs)
        NewIssueLocationForm.__init__(self, *args, **kwargs)


class SearchIssueForm(forms.Form):
    start_date = forms.DateTimeField(label=_('Start Date'))
    end_date = forms.DateTimeField(label=_('End Date'))
    code = forms.CharField(label=_('ID Number / Access Code'))
    assigned_to = forms.ChoiceField()
    category = forms.ChoiceField()
    type = forms.ChoiceField()
    status = forms.ChoiceField()
    region = forms.ChoiceField()
    prefecture = forms.ChoiceField()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        grm_db = get_db(COUCHDB_GRM_DATABASE)

        self.fields['start_date'].widget.attrs['class'] = self.fields['end_date'].widget.attrs[
            'class'] = 'form-control datetimepicker-input'
        self.fields['start_date'].widget.attrs['data-target'] = '#start_date'
        self.fields['end_date'].widget.attrs['data-target'] = '#end_date'
        self.fields['assigned_to'].widget.choices = get_government_worker_choices()
        self.fields['category'].widget.choices = get_issue_category_choices(grm_db)

src/dashboard/authentication/views.py
from django.shortcuts import render
from rest_framework import status


def handler400(request, exception):
    return render(
        request,
        template_name='common/400.html',
        status=status.HTTP_400_BAD_REQUEST,
        content_type='text/html'
    )


def handler403(request, exception):
    return render(
        request,
        template_name='common/403.html',
        status=status.HTTP_403_FORBIDDEN,
        content_type='text/html'
    )


def handler404(request, exception):
    return render(
        request,
        template_name='common/404.html',
        status=status.HTTP_404_NOT_FOUND,
        content_type='text/html'
    )


def handler500(request):
    return render(
        request,
        template_name='common/500.html',
        status=status.HTTP_500_INTERNAL_SERVER_ERROR,
        content_type='text/html'
    )

src/dashboard/logs/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.translation import gettext_lazy as _
from django.views import generic

from dashboard.mixins import PageMixin


class DashboardTemplateView(PageMixin, LoginRequiredMixin, generic.TemplateView):
    template_name = 'common/under_construction.html'
    title = _('Logs')
    active_level1 = 'logs'

src/dashboard/subprojects/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.translation import gettext_lazy as _
from django.views import generic

from dashboard.mixins import PageMixin


class DashboardTemplateView(PageMixin, LoginRequiredMixin, generic.TemplateView):
    template_name = 'common/under_construction.html'
    title = _('Subprojects')
    active_level1 = 'subprojects'

src/dashboard/templates/grm/new_issue_contact.html
{% extends 'layouts/base.html' %}
{% load bootstrap4 static i18n %}

{% block progress-bar %}
    {% include 'common/progress_bar.html' with percentage=16 %}
{% endblock progress-bar %}

{% block content %}
    <div class="row">
        <div class="col-12">
            <div class="card">
                <img src="{% static 'images/bg-left-horizontal-waves.png' %}" class="bg-left-horizontal-waves"/>
                <form method="post">{% csrf_token %}
                    <div class="card-body">
                        <div class="row">
                            <div class="col-12">
                                <div class="fs20 lh46 mb-1 text-regular-family">
                                    Entrer une nouvelle reclamation
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-6">
                                <div class="fs56 lh46 text-primary text-bold-family mb-4">
                                    {% translate 'Step' %} 1
                                </div>
                                <div class="fs35 lh35 text-bold-family ">
                                    Methode préférer de contact
                                </div>
                            </div>
                            <div class="col-6">
                                <span class="fs17 lh18">
                                    {{ form.contact_medium.label_tag }}
                                </span>
                                {% bootstrap_field form.contact_medium show_label=False %}
                                <div class="ml-4">
                                    <div class="row">
                                        <div class="col-6">
                                            {% bootstrap_field form.contact_type %}
                                        </div>
                                        <div class="col-6">
                                            {% bootstrap_field form.contact %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer mb-2">
                        <button type="submit" class="btn btn-primary btn-sm rounded-xl float-right mt-4">
                            ENREGISTRER ET CONTINUER
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block select2 %}
    <script type="text/javascript">
        $("#id_contact_type").select2({
            placeholder: "{% translate 'Click to select contact method' %}",
            allowClear: true,
            disabled: {% if doc.contact_information %}false{% else %}true{% endif %}
        });
    </script>
{% endblock select2 %}

{% block javascript %}
    {{ block.super }}
    <script type="text/javascript">
        $('b[role="presentation"]').hide();
        $('.select2-selection__arrow').append(
            '<i class="fas fa-chevron-circle-down text-primary" style="margin-top:12px;"></i>');

        let contact_type = $('#id_contact_type');
        let contact = $('#id_contact');

        function toggleContactInputs() {
            if ($('#id_contact_medium_2').is(':checked')) {
                contact_type.prop("disabled", false).prop("required", true);
                if (contact.val()) {
                    contact.prop("disabled", false).prop("required", true);
                } else {
                    contact.prop("disabled", true)
                }
                contact.show()
            } else {
                contact_type.prop("disabled", true).prop("required", false).val(null).trigger('change');
                contact.prop("disabled", true).prop("required", false).val('').hide();
            }
        }

        toggleContactInputs();
        $('#id_contact_medium').click(function () {
            toggleContactInputs()
        });
        contact_type.on('select2:select', function (e) {
            contact.prop("disabled", false).prop("required", true);
        });
        contact_type.on('select2:clear', function (e) {
            contact.prop("disabled", true).prop("required", false).val('');
        });
    </script>
{% endblock javascript %}

src/dashboard/templates/grm/review_issues.html
{% extends 'layouts/base.html' %}
{% load bootstrap4 static i18n %}

{% block content %}
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="row issues-filter">
                        <div class="col-4 text-left">
                            <div class="fs28 lh35 text-primary text-bold-family mb-4">
                                {% translate 'Search Results' %}<br>
                            </div>
                            <div class="row mr-5">
                                <div class="col-12">
                                    {% bootstrap_field form.start_date layout='horizontal' %}
                                    {% bootstrap_field form.end_date layout='horizontal' %}
                                </div>
                            </div>
                        </div>
                        <div class="col-8 border-left">
                            <div class="row">
                                <div class="col-2">
                                    <label class="label-align">{% translate 'Filter by' %}</label>
                                </div>
                                <div class="col-5">
                                    {% bootstrap_field form.code show_label=False %}
                                    {% if not user.governmentworker %}
                                        {% bootstrap_field form.assigned_to show_label=False %}
                                    {% endif %}
                                    {% bootstrap_field form.category show_label=False %}
                                </div>
                                <div class="col-5">
                                    {% bootstrap_field form.type show_label=False %}
                                    {% bootstrap_field form.status show_label=False %}
                                </div>
                            </div>
                        </div>
                    </div>
                    <a class="btn fs12 text-bold-family text-primary pull-right p-0"
                       id="clear_all_filters">
                        {% translate "Clear all filters" %}
                    </a>
                </div>
            </div>
            <div class="card">
                <div class="card-body table-responsive">
                    <div id="issue-list"></div>
                    <div class="text-right">
                        <a id="previous" class="btn text-primary hidden">
                            <i class="fa fa-chevron-left fs20 align-middle"></i>
                        </a>
                        <div id="current-page" class="d-inline-block fs14 text-regular-family ml-4 mr-4"></div>
                        <a id="next" class="btn text-primary hidden">
                            <i class="fa fa-chevron-right fs20 align-middle"></i>
                        </a>
                    </div>
                </div>
                <div class="overlay" id="spin">
                    <i class="fas fa-2x fa-sync-alt fa-spin"></i>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascript %}
    {{ block.super }}

    <script type="text/javascript">
        let spin = $('#spin');
        let index = 0;
        const offset = 10;
        let previous = $('#previous');
        let next = $('#next');
        let issues = $('#issue-list');
        let total_issues = 0;
        let current_page = $('#current-page');
        let start_date = $('#id_start_date');
        let end_date = $('#id_end_date');
        let code = $('#id_code');
        let assigned_to = $('#id_assigned_to');
        let category = $('#id_category');
        let type = $('#id_type');
        let status = $('#id_status');

        function loadIssues() {
            spin.show();
            $.ajax({
                type: "GET",
                url: "{% url 'dashboard:grm:issue_list' %}",
                data: {
                    index: index,
                    offset: offset,
                    start_date: start_date.val(),
                    end_date: end_date.val(),
                    code: code.val(),
                    assigned_to: assigned_to.val(),
                    category: category.val(),
                    type: type.val(),
                    status: status.val(),
                },
                success: function (response) {
                    spin.hide();
                    if (index - offset >= 0) {
                        previous.show();
                    } else {
                        previous.hide();
                    }
                    if (index + offset < total_issues) {
                        next.show();
                    } else {
                        next.hide();
                    }
                    issues.html(response);
                    if (response.trim()) {
                        current_page.html(Math.floor(index / offset) + 1 + " / " + Math.ceil(total_issues / offset));
                    } else {
                        current_page.html("")
                    }
                },
                error: function (data) {
                    spin.hide();
                    alert(error_server_message + "Error rrrr " + data.status);
                    current_page.html("");
                }
            });
        }

        function setTotalIssues() {
            $.ajax({
                type: "GET",
                url: "{% url 'dashboard:couchdb_proxy:issues_statistics' %}",
                success: function (response) {
                    total_issues = response['count'];
                    loadIssues();
                },
                error: function (data) {
                    console.log(data)
                    alert(error_server_message + "Error rrrrr " + data.status);
                }
            });
        }

        previous.click(function () {
            index -= offset;
            loadIssues();
        });

        next.click(function () {
            index += offset;
            loadIssues();
        });

        setTotalIssues();

        let dp1 = '<div class="input-group-prepend" data-target="#{id}" data-toggle="datetimepicker">' +
            '<div class="input-group-text"><i class="fa fa-calendar text-primary"></i></div></div>';
        let dp2 = '<div class="input-group date" id="{id}" data-target-input="nearest"></div>';
        $('#id_start_date').before(dp1.replace('{id}', 'start_date')).parent().wrapInner(
            dp2.replace('{id}', 'start_date'));
        $('#id_end_date').before(dp1.replace('{id}', 'end_date')).parent().wrapInner(
            dp2.replace('{id}', 'end_date'));

        //Datemask dd/mm/yyyy
        $('.datetimepicker-input').inputmask({alias: "datetime", inputFormat: "dd/mm/yyyy"});

        let options = {
            maxDate: Date.now(),
            useCurrent: false,
            format: "DD/MM/YYYY",
            widgetPositioning: {
                vertical: 'bottom',
            }
        };

        function dateChanged(e) {
            if (e.oldDate !== e.date) {
                loadIssues();
            }
        }

        $('#start_date').datetimepicker(options);
        $('#start_date').on("change.datetimepicker", dateChanged);
        $('#end_date').datetimepicker(options);
        $('#end_date').on("change.datetimepicker", dateChanged);
        $('.issues-filter input').on('change keyup', function () {
            if (!$(this).val()) {
                loadIssues();
            }
        });
        code.on('change keyup', delay(function () {
            if ($(this).val()) {
                loadIssues();
            }
        }, 500));
        $('.issues-filter select').on('change', function () {
            loadIssues();
        });

        $("#clear_all_filters").on("click", function () {
            $('.issues-filter input').val('');
            $('.issues-filter select').val(null).trigger('change.select2');
            loadIssues();
        });

    </script>
{% endblock %}

{% block select2 %}
    <script type="text/javascript">
        $("#id_assigned_to").select2({
            placeholder: "{% translate 'Assigned to' %}",
            allowClear: true
        });
        $("#id_category").select2({
            placeholder: "{% translate 'Category' %}",
            allowClear: true
        });
        $("#id_type").select2({
            placeholder: "{% translate 'Type' %}",
            allowClear: true,
        });
        $("#id_status").select2({
            placeholder: "{% translate 'Status' %}",
            allowClear: true,
        });

        $('b[role="presentation"]').hide();
        $('.select2-selection__arrow').append(
            '<i class="fas fa-chevron-circle-down text-primary" style="margin-top:12px;"></i>');

    </script>
{% endblock select2 %}