src/dashboard/adls/urls.py
from django.urls import path

from dashboard.adls import views

app_name = 'adls'
urlpatterns = [
    path('', views.AdlListView.as_view(), name='list'),
    path('<slug:id>/', views.AdlDetailView.as_view(), name='detail'),
    path('toggle-status/<slug:id>/', views.ToggleAdlStatusView.as_view(), name='toggle_status'),
    path('edit-profile/<slug:id>/', views.EditAdlProfileFormView.as_view(), name='edit_profile'),
]

src/dashboard/grm/urls.py
from django.urls import path

from dashboard.grm import views

app_name = 'grm'
urlpatterns = [
    path('', views.DashboardTemplateView.as_view(), name='dashboard'),
    path('start-new-issue', views.StartNewIssueView.as_view(), name='start_new_issue'),
    path('upload-issue-attachment/<int:issue>/', views.UploadIssueAttachmentFormView.as_view(),
         name='upload_issue_attachment'),
    path('delete-issue-attachment/<int:issue>/<str:attachment>/', views.IssueAttachmentDeleteView.as_view(),
         name='delete_issue_attachment'),
    path('issue-attachments/<int:issue>/', views.IssueAttachmentListView.as_view(), name='issue_attachments'),
    path('new-issue-step-1/<int:issue>/', views.NewIssueContactFormView.as_view(), name='new_issue_step_1'),
    path('new-issue-step-2/<int:issue>/', views.NewIssuePersonFormView.as_view(), name='new_issue_step_2'),
    path('new-issue-step-3/<int:issue>/', views.NewIssueDetailsFormView.as_view(), name='new_issue_step_3'),
    path('new-issue-step-4/<int:issue>/', views.NewIssueLocationFormView.as_view(), name='new_issue_step_4'),
    path('new-issue-step-5/<int:issue>/', views.NewIssueConfirmFormView.as_view(), name='new_issue_step_5'),
    path('new-issue-step-6/<int:issue>/', views.NewIssueConfirmationFormView.as_view(), name='new_issue_step_6'),
    path('review-issues', views.ReviewIssuesFormView.as_view(), name='review_issues'),
    path('issue-list', views.IssueListView.as_view(), name='issue_list'),
    path('issue-detail/<int:issue>/', views.IssueDetailsFormView.as_view(), name='issue_detail'),
    path('get-sensitive-issue-data/', views.GetSensitiveIssueDataView.as_view(), name='get_sensitive_issue_data'),
    path('edit-issue/<int:issue>/', views.EditIssueView.as_view(), name='edit_issue'),
    path('add-comment-to-issue/<int:issue>/', views.AddCommentToIssueView.as_view(), name='add_comment_to_issue'),
    path('issue-comments/<int:issue>/', views.IssueCommentListView.as_view(), name='issue_comments'),
    path('issue-status-buttons/<int:issue>/', views.IssueStatusButtonsTemplateView.as_view(),
         name='issue_status_buttons'),
    path('submit-issue-open-status/<int:issue>/', views.SubmitIssueOpenStatusView.as_view(),
         name='submit_issue_open_status'),
    path('submit-issue-research-result/<int:issue>/', views.SubmitIssueResearchResultFormView.as_view(),
         name='submit_issue_research_result'),
    path('submit-issue-reject-reason/<int:issue>/', views.SubmitIssueRejectReasonFormView.as_view(),
         name='submit_issue_reject_reason'),
    path('get-choices-for-next-administrative-level', views.GetChoicesForNextAdministrativeLevelView.as_view(),
         name='get_choices_for_next_administrative_level'),
    path('get-ancestor-administrative-levels', views.GetAncestorAdministrativeLevelsView.as_view(),
         name='get_ancestor_administrative_levels'),
]

src/dashboard/urls.py
from django.conf.urls import include
from django.urls import path

app_name = 'dashboard'
urlpatterns = [
    path('', include('dashboard.authentication.urls')),
    path('diagnostics/', include('dashboard.diagnostics.urls')),
    path('administrative-levels/', include('dashboard.adls.urls')),
    # path('participatory-budget/', include('dashboard.participatory_budget.urls')),
    # path('subprojects/', include('dashboard.subprojects.urls')),
    path('grm/', include('dashboard.grm.urls')),
    path('logs/', include('dashboard.logs.urls')),
    path('couchdb-proxy/', include('dashboard.couchdb_proxy.urls')),
]

src/grm/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

handler400 = 'dashboard.authentication.views.handler400'
handler403 = 'dashboard.authentication.views.handler403'
handler404 = 'dashboard.authentication.views.handler404'
handler500 = 'dashboard.authentication.views.handler500'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('attachments/', include('attachments.urls')),
    path('authentication/', include('authentication.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('dashboard.urls')),
]

schema_view = get_schema_view(
    openapi.Info(
        title="GRM API Documentation",
        default_version='v1',
        description="Test Documentation",
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    ]

src/dashboard/authentication/forms.py
from django.contrib.auth import authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext as _

from authentication.models import User


class EmailAuthenticationForm(AuthenticationForm):
    def __init__(self, request=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = _('Email')

    def clean(self):
        email = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        user = User.objects.filter(email__iexact=email).first()

        if not user:
            raise self.get_invalid_login_error()
        if email and password:
            self.user_cache = authenticate(self.request, username=user.username, password=password)
            if self.user_cache is None:
                raise self.get_invalid_login_error()
            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data

src/dashboard/forms/widgets.py
from django import forms


class RadioSelect(forms.RadioSelect):
    input_type = 'radio'
    option_template_name = 'widgets/radio_option.html'

src/dashboard/participatory_budget/forms.py
from datetime import datetime

from django import forms
from django.utils.translation import gettext_lazy as _

from client import get_db
from grm.utils import get_month_range


class CommuneSelectForm(forms.Form):
    commune = forms.ChoiceField()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        view_result = get_db().get_view_result('communes', 'updated_tasks', group=True)
        communes = [(c['key'][0], c['key'][1]) for c in view_result]
        self.fields['commune'].widget.choices = [('', '')] + communes
        self.fields['commune'].widget.attrs['class'] = 'form-control'


class MonthSelectForm(forms.Form):
    month = forms.ChoiceField(label=_("Show:"))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        phases = get_db().get_view_result('phases', 'tasks_by_month', group=True)[0]
        if phases:
            older_phase = phases[0]['key']
            start_date = datetime.strptime(f'{older_phase[0]}-{older_phase[1]}', '%Y-%m')
            month_range = get_month_range(start_date)
            current_month = month_range[0]
            default_option = [(current_month[0], _("This month"))]
            self.fields['month'].widget.choices = default_option + month_range[1:]

src/dashboard/adls/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render
from django.templatetags.static import static
from django.urls import reverse, reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views import generic

from authentication import ADL
from authentication.models import User
from authentication.utils import get_validation_code
from client import COUCHDB_ATTACHMENT_DATABASE, get_db, upload_file
from dashboard.adls.forms import AdlProfileForm, PasswordConfirmForm
from dashboard.mixins import AJAXRequestMixin, JSONResponseMixin, ModalFormMixin, PageMixin


class AdlListView(PageMixin, LoginRequiredMixin, generic.ListView):
    template_name = 'adls/list.html'
    context_object_name = 'adls'
    title = _('Administrative Levels')
    active_level1 = 'adls'
    breadcrumb = [
        {
            'url': '',
            'title': title
        },
    ]

    def get_queryset(self):
        eadl_db = get_db()
        return eadl_db.get_query_result({"type": {"$eq": ADL}})


class ADLMixin(object):
    doc = None

    def dispatch(self, request, *args, **kwargs):
        eadl_db = get_db()
        try:
            self.doc = eadl_db[kwargs['id']]
            if self.doc['type'] != ADL:
                raise Http404
        except Exception:
            raise Http404
        return super().dispatch(request, *args, **kwargs)


class AdlDetailView(ADLMixin, PageMixin, LoginRequiredMixin, generic.DetailView):
    template_name = 'adls/profile.html'
    context_object_name = 'adl'
    title = _('Facilitator Profile')
    active_level1 = 'adls'
    model = User
    breadcrumb = [
        {
            'url': reverse_lazy('dashboard:adls:list'),
            'title': _('Administrative Levels')
        },
        {
            'url': '',
            'title': title
        }
    ]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['password_confirm_form'] = PasswordConfirmForm()
        return context

    def get_object(self, queryset=None):
        return self.doc


class ToggleAdlStatusView(LoginRequiredMixin, generic.View):

    def post(self, request, *args, **kwargs):
        doc_id = kwargs['id']
        eadl_db = get_db()
        try:
            document = eadl_db[doc_id]
            if document['type'] != ADL:
                raise Http404

            if document['representative']['is_active']:
                form = PasswordConfirmForm(request.POST)
                if not form.is_valid():
                    raise PermissionDenied()

                current_user = request.user
                password = form.cleaned_data['password']
                if not current_user.check_password(password):
                    raise PermissionDenied()

                document['representative']['is_active'] = False
                document.save()
                msg = _("The account was successfully deactivated.")
                messages.add_message(request, messages.SUCCESS, msg, extra_tags='success')
            else:
                document['representative']['is_active'] = True
                document.save()
                msg = _("The account was activated successfully.")
                messages.add_message(request, messages.SUCCESS, msg, extra_tags='success')

        except PermissionDenied:
            msg = _("The password was not correct, we could not proceed with action.")
            messages.add_message(request, messages.ERROR, msg, extra_tags='danger')
        except Exception:
            raise Http404

        return HttpResponseRedirect(reverse('dashboard:adls:detail', args=[doc_id]))


class EditAdlProfileFormView(ADLMixin, AJAXRequestMixin, ModalFormMixin, LoginRequiredMixin, JSONResponseMixin,
                             generic.FormView):
    form_class = AdlProfileForm
    title = _('Profile information')
    picture = static('images/default-avatar.jpg')
    picture_class = "edit-profile-user-img"
    submit_button = _('Save')

    def get_context_data(self, **kwargs):
        picture = self.doc["representative"]["photo"] if "photo" in self.doc["representative"] else ""
        if picture:
            self.picture = picture
        context = super().get_context_data(**kwargs)
        return context

    def get_form_kwargs(self):
        self.initial = {'doc_id': self.doc['_id']}
        return super().get_form_kwargs()

    def form_valid(self, form):
        data = form.cleaned_data
        doc = self.doc
        photo = doc["representative"]["photo"] if "photo" in doc["representative"] else ""
        if data['file']:
            response = upload_file(data['file'])
            if response['ok']:
                if photo:
                    attachment_db = get_db(COUCHDB_ATTACHMENT_DATABASE)
                    attachment_id = photo.split('/')[2]
                    try:
                        attachment_db[attachment_id].delete()
                    except Exception:
                        pass
                photo = f'/attachments/{response["id"]}/{data["file"].name}'
                doc["representative"]["photo"] = photo
            else:
                msg = _("An error has occurred that did not allow the profile picture to be uploaded to the database. "
                        "Please report to IT staff.")
                messages.add_message(self.request, messages.ERROR, msg, extra_tags='danger')
        doc['representative']['name'] = data['name']
        doc['representative']['phone'] = data['phone']
        email = data['email'].lower()
        adl_code = get_validation_code(email)
        if doc['representative']['email'] != email:
            msg = _("Please note that the Facilitator Code has changed due to the email change.")
            messages.add_message(self.request, messages.INFO, msg, extra_tags='info')
        doc['representative']['email'] = email
        doc.save()

        msg = _("The profile information was successfully edited.")
        messages.add_message(self.request, messages.SUCCESS, msg, extra_tags='success')
        context = {
            'msg': render(self.request, 'common/messages.html').content.decode("utf-8"),
            'adl_code': adl_code,
            'photo': photo,
        }
        return self.render_to_json_response(context, safe=False)

src/dashboard/authentication/views.py
from django.shortcuts import render
from rest_framework import status


def handler400(request, exception):
    return render(
        request,
        template_name='common/400.html',
        status=status.HTTP_400_BAD_REQUEST,
        content_type='text/html'
    )


def handler403(request, exception):
    return render(
        request,
        template_name='common/403.html',
        status=status.HTTP_403_FORBIDDEN,
        content_type='text/html'
    )


def handler404(request, exception):
    return render(
        request,
        template_name='common/404.html',
        status=status.HTTP_404_NOT_FOUND,
        content_type='text/html'
    )


def handler500(request):
    return render(
        request,
        template_name='common/500.html',
        status=status.HTTP_500_INTERNAL_SERVER_ERROR,
        content_type='text/html'
    )

src/dashboard/couchdb_proxy/views.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic

from client import get_db
from dashboard.mixins import AJAXRequestMixin, JSONResponseMixin

COUCHDB_GRM_DATABASE = settings.COUCHDB_GRM_DATABASE


class StatisticsOfTasksUpdatedByRegionView(AJAXRequestMixin, LoginRequiredMixin, JSONResponseMixin, generic.View):
    def get(self, request, *args, **kwargs):
        eadl_db = get_db()
        administrative_id = self.request.GET.get('administrative_id', None)
        if administrative_id:
            stats = eadl_db.get_view_result('tasks', 'updated_by_administrative_region_stats',
                                            key=administrative_id)
        else:
            stats = eadl_db.get_view_result('tasks', 'updated_by_administrative_region_stats')

        if stats[0]:
            stats = stats[0][0]['value']
        else:
            stats = {'count': 0}

        return self.render_to_json_response(stats, safe=False)


class IssuesStatisticsView(AJAXRequestMixin, LoginRequiredMixin, JSONResponseMixin, generic.View):
    def get(self, request, *args, **kwargs):
        grm_db = get_db(COUCHDB_GRM_DATABASE)

        if hasattr(self.request.user, 'governmentworker'):
            issues_stats = grm_db.get_view_result('issues', 'by_assignee_stats', key=self.request.user.id)
        else:
            issues_stats = grm_db.get_view_result('issues', 'by_assignee_stats')

        if issues_stats[0]:
            issues_stats = issues_stats[0][0]['value']
        else:
            issues_stats = {'count': 0}

        return self.render_to_json_response(issues_stats, safe=False)

src/dashboard/logs/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.translation import gettext_lazy as _
from django.views import generic

from dashboard.mixins import PageMixin


class DashboardTemplateView(PageMixin, LoginRequiredMixin, generic.TemplateView):
    template_name = 'common/under_construction.html'
    title = _('Logs')
    active_level1 = 'logs'

src/dashboard/subprojects/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.translation import gettext_lazy as _
from django.views import generic

from dashboard.mixins import PageMixin


class DashboardTemplateView(PageMixin, LoginRequiredMixin, generic.TemplateView):
    template_name = 'common/under_construction.html'
    title = _('Subprojects')
    active_level1 = 'subprojects'

src/dashboard/templates/participatory_budget/dashboard.html
{% extends 'layouts/base.html' %}
{% load bootstrap4 static i18n %}

{% block content %}
    {% translate 'Completed' as completed %}
    <div class="row">
        <div class="col-lg-7">
            <div class="card tasks-updated">
                <div class="card-header pt-4 pr-4 pb-1 border-0">
                    <div class="card-title">
                        <div class="communes-performed">
                            {{ communes_served }}/{{ total_communes }}
                        </div>
                        <div class="fs15">
                            {% translate 'Have started the participatory budgeting process' %}
                        </div>
                    </div>
                    <div class="card-tools">
                        <div class="input-group mb-3 search-bar-select">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fas fa-search"></i></span>
                            </div>
                            {{ commune_select_form.commune }}
                        </div>
                    </div>
                </div>
                <div class="card-header pt-0">
                    <div class="progress height8 rounded-lg">
                        {% widthratio communes_served total_communes 100 as communes_performed %}
                        <div class="progress-bar bg-custom-gradient-primary" role="progressbar"
                             aria-valuenow="{{ communes_performed }}" aria-valuemin="0" aria-valuemax="100"
                             style="width: {{ communes_performed }}%">
                            <span class="sr-only">{{ communes_performed }}% {{ completed }}</span>
                        </div>
                    </div>
                    <div class="title mt-4">
                        {% translate 'Updated Tasks' %}
                    </div>
                </div>
                <div class="card-body overflow-y-auto" style="height: 592px;">
                    <div id="task-list">{% translate 'No notifications found' %}</div>
                    <div class="text-center">
                        <button class="btn btn-link-primary fs12" id="more-tasks" disabled>
                            {% translate 'Load more notifications' %}
                        </button>
                    </div>
                </div>
                <div class="overlay" id="tasks-updated-spin">
                    <i class="fas fa-2x fa-sync-alt fa-spin"></i>
                </div>
            </div>
        </div>
        <div class="col-lg-5 display-flex flex-flow-column">
            <div class="card bg-gradient-custom-green">
                <div class="card-header border-0">
                    <div class="card-title">
                        <div class="pt-1 fs15 lh23 text-bold-family">
                            {% translate 'Average budget allocated to the BP' %}
                        </div>
                    </div>
                    <div class="card-tools">
                        <a href="#" class="btn btn-xs bg-white text-custom-green">
                            {% translate 'See the communes' %}
                        </a>
                    </div>
                </div>
                <div class="card-body">
                    <div class="fs38 lh30">200.000.000 GNF</div>
                </div>
            </div>
            <div class="card h-100">
                <div class="card-header pt-4 pr-4 pb-1">
                    <div class="card-title">
                        <div class="fs15 text-primary text-bold-family">
                            {% translate 'Participatory Budget Statement' %}
                        </div>
                    </div>
                    <div class="card-tools transparent-select">
                        {% bootstrap_field month_select_form.month %}
                    </div>
                </div>
                <div class="card-body" id="statement">

                </div>
                <div class="overlay" id="statement-spin">
                    <i class="fas fa-2x fa-sync-alt fa-spin"></i>
                </div>
            </div>
        </div>
    </div>
{% endblock %}


{% block select2 %}
    <script type="text/javascript">
        $("#id_commune").select2({
            placeholder: "{% translate 'Search' %}...",
            allowClear: true
        });
        $("#id_month").select2({
            width: '115px'
        });
    </script>
{% endblock select2 %}

{% block javascript %}
    {{ block.super }}
    <script type="text/javascript">
        let commune = $('#id_commune');

        commune.on('change', function () {
            index = 0;
            setTotalTasks();
        });

        // Tasks Updated -----------------------------------------------------------------------------------------------

        let tasks_updated_spin = $('#tasks-updated-spin');
        let index = 0;
        const offset = 10;
        let more = $('#more-tasks');
        let tasks = $('#task-list');
        let total_tasks = 0;

        function loadTasks() {
            tasks_updated_spin.show();
            $.ajax({
                type: "GET",
                url: "{% url 'dashboard:participatory_budget:updated_task_list' %}",
                data: {
                    index: index,
                    offset: offset,
                    commune: commune.val(),
                },
                success: function (response) {
                    tasks_updated_spin.hide();
                    if (index < total_tasks) {
                        more.prop('disabled', false);
                        if (index === 0) {
                            tasks.html(response);
                        } else {
                            tasks.append(response);
                        }
                        index += offset;
                    } else {
                        more.prop('disabled', true);
                    }
                },
                error: function (data) {
                    tasks_updated_spin.hide();
                    alert(error_server_message + "Error " + data.status);
                }
            });
        }

        function setTotalTasks() {
            $.ajax({
                type: "GET",
                url: "{% url 'dashboard:couchdb_proxy:statistics_region_updated_tasks' %}",
                data: {
                    commune: commune.val(),
                },
                success: function (response) {
                    total_tasks = response['count'];
                    loadTasks();
                },
                error: function (data) {
                    alert(error_server_message + "Error " + data.status);
                }
            });
        }

        setTotalTasks();
        more.click(function () {
            loadTasks();
        });

        // Statement ---------------------------------------------------------------------------------------------------

        let statement_spin = $('#statement-spin');
        let month = $('#id_month');

        function loadStatement() {
            statement_spin.show();
            $.ajax({
                type: "GET",
                url: "{% url 'dashboard:participatory_budget:statement' %}",
                data: {
                    month: month.val(),
                },
                success: function (response) {
                    statement_spin.hide();
                    $('#statement').html(response);
                },
                error: function (data) {
                    statement_spin.hide();
                    alert(error_server_message + "Error " + data.status);
                }
            });
        }

        month.on('change', function () {
            loadStatement();
        });

        $(document).ready(function () {
            loadStatement();
        });
    </script>

{% endblock javascript %}

src/dashboard/templates/participatory_budget/statement.html
{% load custom_tags i18n %}

{% translate 'Completed' as completed %}

{% for phase in phases %}
    <div class="mb-1 d-table w-100">
        <div class="d-table-cell">
            <div class="progress rounded-lg height22 mr-1">
                <div class="progress-bar navbar-{{ colors|next_in_circular_list:forloop.counter0 }} rounded-lg"
                     role="progressbar" aria-valuenow="5"
                     aria-valuemin="0" aria-valuemax="100" style="width: {{ phase.performance }}%">
                    <span class="sr-only">{{ phase.performance }}% {{ completed }}</span>
                </div>
            </div>
        </div>
        <div class="bp-badges">
            <div class="navbar-white">{{ phase.completed_tasks }}</div>
            <div class="badge-{% get_percentage_style phase.performance %}">{{ phase.performance }}%</div>
        </div>
    </div>
{% empty %}
    {% translate 'Month without budget statement' %}
{% endfor %}
<div class="border-separator mt-2 mb-1"></div>
{% for phase in phases %}
    <div class="">
        <div class="bp-badge-legend navbar-{{ colors|next_in_circular_list:forloop.counter0 }}"></div>
        <div class="legend-text">{{ phase.title }}</div>
    </div>
{% endfor %}

src/dashboard/templates/participatory_budget/task_list.html
{% load custom_tags i18n %}

{% for data in tasks %}
    {% with data.value.task as task %}
        <div class="card-item">
            <div class="row">
                <div class="col-8">
                    <div class="text-bold-family fs13 lh20">{% translate 'Task' %}:</div>
                    <div class="fs14 lh16">{{ task.title }}</div>
                </div>
                <div class="col-4 text-right">
                    <div class="fs13 lh20">{% get_date task.updated_at %}</div>
                </div>
            </div>
            <div class="row">
                <div class="col-8 mt-2">
                    <div class="fs13 lh14">
                        <span class="text-bold-family ">{% translate 'Phase' %}:</span> {{ data.value.phase.title }}
                    </div>
                    <div class="fs13 lh14 mt-1">
                        <span class="text-bold-family ">{% translate 'Commune' %}:</span> {{ data.value.commune }}
                    </div>
                </div>
                <div class="col-4 text-right">
                    <div class="status-badge badge-{{ task.status }}">
                        {% if task.status == 'completed' %}
                            {% translate 'Completed' %}
                        {% elif task.status == 'in-progress' %}
                            {% translate 'In progress' %}
                        {% else %}
                            {% translate 'Pending' %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    {% endwith %}
{% endfor %}